// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOd-QKSY_KeOCjkM_ZYvvtQ_i4VVh1vbY',
    appId: '1:943494248130:web:906b56ab6a7a03e2582d5b',
    messagingSenderId: '943494248130',
    projectId: 'food-rescue-2326e',
    authDomain: 'food-rescue-2326e.firebaseapp.com',
    storageBucket: 'food-rescue-2326e.firebasestorage.app',
    measurementId: 'G-MKR3J63MFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgspeKSAIBz-Km2kY3MiJOhfN41Y1m44',
    appId: '1:943494248130:android:d9d58bcee59c5e0c582d5b',
    messagingSenderId: '943494248130',
    projectId: 'food-rescue-2326e',
    storageBucket: 'food-rescue-2326e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFCT_dTCl5dBW_SH-Z3eQUfRCHmqzCq3o',
    appId: '1:943494248130:ios:f0f988f461be3dbc582d5b',
    messagingSenderId: '943494248130',
    projectId: 'food-rescue-2326e',
    storageBucket: 'food-rescue-2326e.firebasestorage.app',
    iosBundleId: 'com.example.foodRescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFCT_dTCl5dBW_SH-Z3eQUfRCHmqzCq3o',
    appId: '1:943494248130:ios:f0f988f461be3dbc582d5b',
    messagingSenderId: '943494248130',
    projectId: 'food-rescue-2326e',
    storageBucket: 'food-rescue-2326e.firebasestorage.app',
    iosBundleId: 'com.example.foodRescue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOd-QKSY_KeOCjkM_ZYvvtQ_i4VVh1vbY',
    appId: '1:943494248130:web:9ae1ac2724657c0b582d5b',
    messagingSenderId: '943494248130',
    projectId: 'food-rescue-2326e',
    authDomain: 'food-rescue-2326e.firebaseapp.com',
    storageBucket: 'food-rescue-2326e.firebasestorage.app',
    measurementId: 'G-VW1NFX95RB',
  );
}
